#!/usr/bin/env bash
# Script displays information about subdomains
domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")
dig_function() {
	local domain="$1"
	local subdomain="$2"

	dig "$domain" | grep -A1 'ANSWER SECTION:' | sed -r "s/$domain./$subdomain/g" | awk -F" " ' NR==2 { print "The subdomain", $1, "is a", $4, "record and points to", $5 }'
}
if [ -z "$2" ]; then
	for subdomain in "${subdomains[@]}"; do
		URL="${subdomain}.${domain}"
		dig_function "$URL" "$subdomain"
	done
else
	URL="${2}.${domain}"
	dig_function "$URL" "$2"
fi
