#!/usr/bin/env bash
# Script displays information about subdomains
domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")
dig_function() {
	local domain="$1"

	dig "$domain" |grep 
}
if [ -z "$2" ]; then
	for subdomain in "${subdomains[@]}"; do
		URL="${subdomain}.${domain}"
		dig_function "$URL"
	done
else
	URL="${2}.${domain}"
	dig_function "$URL"
fi
