#!/usr/bin/env bash
# Script displays information about subdomains
domain="$1"
subdomains=("www" "lb-01" "web-01" "web-02")
dig_function() {
	local domain="$1"
	local subdomain="$2"

	dig "$domain" | head -n 13 | tail -n 1 | awk '{print "The subdomain $subdomain, "}'
}
if [ -z "$2" ]; then
	for subdomain in "${subdomains[@]}"; do
		URL="${subdomain}.${domain}"
		dig_function "$URL" "$subdomain"
	done
else
	URL="${2}.${domain}"
	dig_function "$URL" "$subdomain"
fi
