#!/usr/bin/env bash
# Script to install nginx on a web server

# Installing nginx
sudo apt update
sudo apt -y install nginx

# configuring thee firewall to allow service
sudo ufw allow 'Nginx HTTP'

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/example.com
sudo service nginx restart
