#!/usr/bin/env bash
# Script to install nginx on a web server

# Installing nginx
sudo apt update
sudo apt -y install nginx

# configuring thee firewall to allow service
sudo ufw allow 'Nginx HTTP'

# creating a copy of the server configuration block
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/test.com

sed -i "s/ default_server
sudo service nginx restart
