#!/usr/bin/env bash
# Script to install nginx on a web server

# Installing nginx
sudo apt update
sudo apt -y install nginx

# configuring thee firewall to allow service
sudo ufw allow 'Nginx HTTP'

# Creating an html doc that prints Hello world when a GET
#+ is made to the root
sudo echo "Hello World!" > /var/www/html/index.html

# creating a copy of the server configuration block
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/test.com

# Set up redirection at /redirect_me to another site
sudo sed -i '24i\      rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# setting up a custom error 404 page
sudo echo "Ceci n'est pas une page" > /var/www/html/error_404_page.html
sudo sed -i "25i\      error_page 404 /var/www/html/error_404_page.html;" 
# Restarting the web server
sudo service nginx restart
