#!/usr/bin/env bash
# Script configures a brand new ubuntu machine and sets up HAProxy

sudo apt update

# installing the load balancer
sudo apt install haproxy

# Setting up the load balancer to manage servers web-01 and web-02
# shellcheck disable=SC2024
sudo echo "" >> /etc/haproxy/haproxy.cfg
# shellcheck disable=SC2024
sudo echo "" >> /etc/haproxy/haproxy.cfg
sudo sed -i "36i\backend web-backend\n        balance roundrobin\n        server web-01 54.152.133.156:80 check\n        server web-02 54.165.176.3:80 check" /etc/haproxy/haproxy.cfg
# shellcheck disable=SC2024
sudo echo "" >> /etc/haproxy/haproxy.cfg
sudo sed -i "41i\frontend web-frontend\n        bind *:80\n        mode http\n        default_backend web-backend" /etc/haproxy/haproxy.cfg

# Restarting the load balancer.
sudo service haproxy restart
