#!/usr/bin/env bash
# Script configures a brand new ubuntu machine,
#+ installs a web server to add a custom header 'X-Served-By' with hostname as value
#+ and also installs a load balancer

host=$(hostname)

# updating apt list
sudo apt update

# installing Nginx web server
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i "45i\\        add_header X-Served-By \"${host}\";" /etc/nginx/sites-available/default
sudo service nginx restart
