#!/usr/bin/env bash
# script generates a MySQL dump and creates a compressed archive out of it.

dd=$(date +"%d")
mm=$(date +"%m")
year=$(date +"%Y")
file="$day-$month-$year.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file" backup.sql
