#!/usr/bin/env bash
# script generates a MySQL dump and creates a compressed archive out of it
#+ which would be named using the format Da.

DD=$(date +"%d")
MM=$(date +"%m")
YYYY=$(date +"%Y")
file="$DD-$MM-$YYYY.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file" backup.sql
