#!/usr/bin/env bash
# script generates a MySQL dump and creates a compressed archive out of it
#+ which would be named using the format '<Day>-<Month>-<Year>.tar.gz'.

DD=$(date +"%d")
MM=$(date +"%m")
YYYY=$(date +"%Y")
file="$DD-$MM-$YYYY.tar.gz"
user_pwd="$1"

mysqldump --all-databases -u root --password="$user_pwd" > backup.sql
tar -czvf "$file" backup.sql
