#!/usr/bin/env bash
# Script makes sure an Nginx server is running, and
#+ listening on port 80 of all the server’s active IPv4 IPs
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
