#!/bin/bash

while getopts ":a:m:d" opt; do
  case $opt in
    d)
      directory="$OPTARG"
      echo "Selected directory: $directory"
      ;;
    a)
      file="$OPTARG"
      echo "Selected file: $file"
      ;;
    \?)
      echo "Invalid option: -$OPTARG"
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument."
      exit 1
      ;;
  esac
done

# Shift the options so that $1, $2, etc. refer to the remaining arguments
shift $((OPTIND-1))

# Additional code using non-option arguments, if any
echo "Remaining arguments: $@"

# Your script logic goes here
