#!/usr/bin/env bash
# Script manages another script "manage_my_process"

if [ "$#" -ne 1 ]; then
	echo "Usage: manage_my_process {start|stop|restart}"
else
	case ${1} in
	"start")
		./manage_my_process &
		sudo echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	"stop")
		if [ -e /var/run/my_process.pid ]; then
			kill -SIGTERM "$(pgrep -f "manage_my_process")"
			sudo rm /var/run/my_process.pid
		fi
		echo "manage_my_process stopped"
		;;
	"restart")
		if [ -e /var/run/my_process.pid ]; then
			kill -SIGTERM "$(pgrep -f "manage_my_process")"
			sudo rm /var/run/my_process.pid
		fi
		./manage_my_process &
		sudo echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
	esac
fi
