#!/usr/bin/env bash
# Script fixes the container so that nginx runs as nginx user
sudo sed -i 's/user *;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default

