#!/usr/bin/env bash
# Check if Gunicorn is running

if pgrep -x "gunicorn" > /dev/null; then
    # Get the process IDs of Gunicorn workers
    worker_pids=$(pgrep gunicorn)

    # Iterate through each worker PID
    for pid in $worker_pids; do
        kill -HUP "$pid"

        # Wait for the worker to finish processing current requests
        while kill -0 "$pid" 2>/dev/null; do
            sleep 1
        done
    done
fi
